---
title: "PREDI"
---
_________
 Bienvenid@ a __PREDI__, la herramienta electoral que ofrece __predicciones diarias__ para el 28A. 
 

A continuaci贸n, los resultados actualizados __[5 de abril de 2019]__. 
 
-------------------

- __[Predicci贸n sobre el gobierno resultante](https://aloport.github.io/predi/gobierno.html)__

```{r, echo = FALSE, fig.align='center'}
myColors_gen <- c("#0000BA", "#9A0000", "#A9A9A9", "#C57420", "#FF3827", "#FF9300", "#04AAFF")
 
library(DT)

datatable(head(generales_little, 4), rownames=FALSE, colnames = c('Tipo de gobierno', 'Probabilidad', 'Tendencia'), extensions = 'FixedColumns',
  options = list(
    dom = 't',
    scrollX = TRUE,
    fixedColumns = TRUE
  )) %>%
  formatStyle(
    'diff',
    color = styleInterval(c(-0.001, 0.001), c('red', 'black', 'green'))
  ) %>%
  formatStyle('type', fontWeight = 'bold')



```

- __[Estimaci贸n de voto a partidos](https://aloport.github.io/predi/voto.html)__

```{r, echo = FALSE, fig.align='center'}


datatable(intrapolation_little, rownames=FALSE, colnames = c('Partido', 'Voto', 'Tendencia'), extensions = 'FixedColumns',
  options = list(
    dom = 't',
    scrollX = TRUE,
    fixedColumns = TRUE
  )) %>%
  formatStyle(
    'diff',
    color = styleInterval(c(-0.001, 0.001), c('red', 'black', 'green'))
  ) %>%
  formatStyle('party', fontWeight = 'bold')

```

```{r, echo = FALSE, fig.align='center'}

library(networkD3)
data(MisLinks, MisNodes)
forceNetwork(Links = MisLinks, Nodes = MisNodes, Source = "source",
             Target = "target", Value = "value", NodeID = "name",
             Group = "group", opacity = 0.4)


```

__________

Contacto: Alberto L贸pez Ortega _alberto.lopezortega@uzh.ch_ , [bertous](https://twitter.com/bertous)
