---
title: ¿Quieres participar?
---

¿Te interesa la política? Nos gustaría invitarte a participar en un mercado de predicción sobre las elecciones generales del 28A y las autonómicas y locales del 26M, disponible en la web http://thepredictionmarket.com. Este mercado de predicción se encuadra en un proyecto de investigación de la Universidad de Zúrich.

El objetivo de este proyecto es crear predicciones adecuadas acerca de los próximos eventos en la política española, tales como las elecciones  generales, locales y autonómicas de este año. Este mercado de predicción se asemeja mucho a un mercado bursátil. Sin embargo, en lugar de comprar y vender productos financieros, los participantes lo hacen con acciones que representan eventos próximos como, por ejemplo, los resultados electorales. 

Como participante en el mercado de predicción puedes demostrar tus conocimientos acerca de la política española y ser recompensado dependiendo de tu rendimiento en el juego. Además, podrás optar de manera opcional a un certificado de participación en este proyecto de investigación incluyendo información acerca de tu rendimiento en el mismo.

## Registro

Puedes registrarte en el mercado de predicción creando una cuenta en http://thepredictionmarket.com. Una vez creada tu cuenta te asignaremos un mercado y enviaremos detalladamente las instrucciones del juego. Para poder identificarte, debes utilizar tu cuenta de e-mail oficial de tu universidad. Este proceso no es automático y podría tardar unos días.

## Remuneración

Para poder comprar y vender en el mercado de predicción te entregaremos 10 euros. Con este dinero deberás comprar y vender acciones sobre eventos políticos. Tu ganancia al final del juego dependerá de tu buen rendimiento. Por ejemplo, en el mercado de las pasadas elecciones catalanas los participantes obtuvieron de media 20,83€; y las ganancias oscilaron desde 0 hasta los 348,53€ que recibió el ganador. Dicha compensación será pagada después del cierre de mercado, cuando se haya elegido formalmente un nuevo gobierno en cada caso. La compensación se transferirá a través de una transferencia bancaria, lo cual solamente será posible a través de cuentas bancarias europeas, registradas con el nombre del participante. 

