---
title: ¿Cómo funciona el mercado de predicción?
---

El mecanismo del mercado de predicción se asemeja mucho al de un mercado bursátil. Sin embargo, en lugar de comerciar con productos financieros, los participantes en el mercado comercian con acciones sobre eventos políticos futuros. En nuestro mercado para las elecciones generales del 28A, por ejemplo, los participantes tienen que predecir dos tipos de eventos. 

- _Estimación de voto._ El primer tipo de evento es el resultado electoral que va a obtener cada uno de los principales partidos en porcentaje de votos. Para ello, tenemos un submercado para cada uno de los cinco grandes partidos (PSOE, PP, Ciudadanos, Unidas Podemos y VOX). Posteriormente, interpolamos las probabilidades acumuladas en un modelo agregado y proyectamos la estimación conjunta que puedes consultar diariamente aquí.  

- _Gobierno resultante._ El segundo evento que tienen que predecir los participantes es cuál va ser el gobierno resultante tras las elecciones, en el que cada uno de los escenarios más probables es un contrato en el mercado. 

En el mercado sobre el gobierno resultante, por ejemplo, los participantes compran y venden un contrato llamado “un gobierno de coalición de izquierdas”, lo cual significa en nuestro mercado que PSOE y al menos otro partido distinto a Ciudadanos formarán el próximo gobierno de España. En cuanto el mercado se pone en marcha, el precio variante de este contrato refleja la probabilidad de que tenga lugar el evento descrito en él. Los participantes pueden comprar acciones si piensan que la probabilidad de que este evento tenga lugar es mayor que la sugerida por su precio y vender acciones si piensan que la probabilidad de dicho evento es menor.

## Ventajas

El mercado de predicción conlleva algunas ventajas sustanciales sobre otros modelos de predicción como las encuestas. En este sentido, la predicción de los resultados cambia en vivo. Es decir, el mercado tiene el potencial de mostrar el efecto directo que tiene un evento, por ejemplo, sobre las expectativas de voto de un partido. Otra ventaja importante es que permite predecir eventos complejos como cuál va a ser el gobierno que conforme tras las próximas elecciones. En este mercado, los participantes tienen que agregar la participación electoral, los resultados esperados de cada partido y la política de pactos que estos pueden seguir. Por último, el mercado tiene una ventaja estratégica y es que, al no ser una encuesta, no está sujeto a prohibiciones de publicación durante la última semana antes de las elecciones.

A diferencia de las encuestas donde las muestra de los participantes debe ser representativa de la población, en nuestro mercado reclutamos participantes interesados por la política (la mayoría de ellos profesores y alumnos de ciencias sociales de universidades españolas). Esto es importante porque su labor consiste en traducir en probabilidades la información a su alcance (encuestas, de elecciones precedentes, noticias, eventos). Como el objetivo es puramente científico, en nuestro mercado los participantes no pueden endeudarse o invertir su propio dinero. En cambio, les entregamos diez euros. Este montante, que puede subir o bajar en función del buen rendimiento del participante mientras transcurre el juego, sirve de incentivo económico para motivar el acierto y bloquear posibles sesgos.

_________________

Contacto: Alberto López Ortega _alberto.lopezortega@uzh.ch_ , [bertous](https://twitter.com/bertous)

